$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
  	responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:3
        }
    },
    pagination:false,
    transitionStyle:"fade",
    navigation:true,
    navigationText:["",""],
    autoPlay:true,
    nav:true,
    loop:true,
  });
});